
import { RegisterErrorType, initClientApp } from 'green_dot'
import mainConfig from '../green_dot.config'

initClientApp(mainConfig)

import sharedErrors from './1_shared/shared.error'
import s3Errors from './aws/s3.error'
export * from './aws/s3MediaManager.svc'
export * from './blockchainInterface/sendJsonFileForExplorerBlockchain.svc'
export * from './dataTracking/dataCleanningProcessing.schedule.svc'
export * from './dataTracking/dataTrackingRegisterEvent.svc'
export * from './brevoIntegration/syncContacts.schedule.svc'
export * from './error-handler/frontendErrorHandler.svc'
export * from './finance/checkTransactionStatus.svc'
import financeErrors from './finance/finance.error'
export * from './finance/getCryptoChartData.svc'
export * from './finance/getCurrencyRateLive.svc'
export * from './finance/getTargetedCurrencyRates.svc'
export * from './finance/transactionStatusServiceAndSchedule.svc'
export * from './ico/addTransactionBonusCode.svc'
export * from './ico/assignWalletToUser.svc'
export * from './ico/cancelTransactionByUser.svc'
export * from './ico/checkTransactionOutdated.schedule.svc'
export * from './ico/checkTransactionsOnBangkWallets.schedule.svc'
export * from './ico/computeIcoTotalRaised.schedule.svc'
export * from './ico/createBangkWalletsAsAdmin.svc'
export * from './ico/createIcoBonus.svc'
export * from './ico/createIcoTransaction.svc'
export * from './ico/getGeneralBonusCode.svc'
export * from './ico/getNbReferralSinceLastPageView.svc'
import icoErrors from './ico/ico.error'
export * from './ico/icoGetAllReferedUsersWithBGKbonus.svc'
export * from './ico/icoTransactionOnUpdateCreate.svc'
export * from './ico/icoTransactionSuccessHandler.svc'
export * from './ico/isBonusCodeValid.svc'
export * from './ico/userHasTransactions.svc'
export * from './jiraIntegration/create-jira-issue.svc'
export * from './kyc/getKycUrl.svc'
import kycErrors from './kyc/kyc.error'
export * from './kyc/kycRequestForRestrictedCountries.svc'
export * from './kyc/manageDueDiligenceStatusAsAdmin.svc'
export * from './kyc/manageKycStatusAsAdmin.svc'
export * from './kyc/shuftiProCallback.svc'
export * from './kyc/updateKycStatus.svc'
export * from './sellOffers/checkSellOfferValidUntil.schedule.svc'
import sellOfferErrors from './sellOffers/sellOffer.error'
export * from './support/sendMessageToSupport.svc'
export * from './testing/triggerServerActionAsSys.svc'
export * from './transaction/addTransactionInfos.svc'
import transactionErrors from './transaction/transaction.error'
export * from './user/checkOrChangeEmailOrPassword.svc'
export * from './user/checkUserExists.svc'
export * from './user/deleteUserRequest.svc'
export * from './user/getNewToken.svc'
export * from './user/registerCompanyRepresentative.svc'
export * from './user/registerUserDevice.svc'
export * from './user/resetUserDev.svc'
export * from './user/secureAuthForTestEnv.svc'
export * from './user/sendEmailVerificationReminder.schedule.svc'
export * from './user/sendKycReminder.schedule.svc'
export * from './user/sendReferralProgramReminder.schedule.svc'
export * from './user/sendUpdateAndValidationAndForgotPasswordEmail.svc'
export * from './user/subscribe.svc'
export * from './user/updateEmail.svc'
export * from './user/updatePassword.svc'
import userErrors from './user/user.error'
export * from './user/userUpdatePhone.svc'
export * from './website/subscribeToNewsletter.svc'
export * from './1_shared/seed/seed-db-app.svc'
export * from './1_shared/seed/seed-db-ico.svc'
export * from './finance/blockchainInterface/getHashFromContractAndUserWallet.schedule.svc'
export * from './ico/plaidIntegration/plaidCheckIcoBankAccountForFunds.schedule.svc'
export * from './ico/plaidIntegration/plaidConnexion.svc'
export * from './user/login/bangkAdminLogin.svc'
export * from './user/login/loginOrSubscribePREPROD.svc'
export * from './user/login/loginWithEmail.svc'
export * from './user/login/logout.svc'


declare global {
  interface GreenDotErrors extends RegisterErrorType<typeof sharedErrors & typeof s3Errors & typeof financeErrors & typeof icoErrors & typeof kycErrors & typeof sellOfferErrors & typeof transactionErrors & typeof userErrors> { }
}
